#项目配置
server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
    testWhileIdle: true
    #获取连接时执行检测，建议关闭，影响性能
    testOnBorrow: false
    #归还连接时执行检测，建议关闭，影响性能
    testOnReturn: false
    #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
    poolPreparedStatements: false
    #开启poolPreparedStatements后生效
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入，去掉后监控界面sql无法统计，'wall'用于防火墙
    #config是为了数据库加密
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录: 500毫秒
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    cachePrepStmts: true
    druid:
      url: jdbc:mysql://localhost:3306/testjava?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

# mybatis-plus 全局配置
mybatis-plus:
  global-config:
    db-config:
      # 不显示 banner 图
      banner: false
      #  主键生成策略 自增组件
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      #      logic-delete-field: delete
      #      logic-delete-value: 0
      #      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

